export const languages = {original:'Original · Raw', en:'English', es:'Español', pt:'Português', de:'Deutsch', fr:'Français', it:'Italiano', ru:'Русский', da:'Dansk'};
export const htmlLang = {original:'lt', en:'en', es:'es', pt:'pt-PT', de:'de', fr:'fr', it:'it', ru:'ru', da:'da'};
const keys = ['notebook','hero','intro','explore','notes','notesIntro','search','originalLanguage','allLanguages','all','about','aboutTitle','aboutText','sport','languages','mind','originalNote','translationNote','viewOriginal','raw','download','back','empty','reset','results','translation','original','skip','minutes','purpose','landscape','footer'];
const data = {
original:[
'ASMENINIS UŽRAŠŲ SĄSIUVINIS','Rašau, kad pats suprasčiau.','Sportas, kalbos ir mintys. Patirtys, prie kurių grįžtu, klausimai, kuriuos dar tyrinėju.','Skaityti užrašus','Užrašai iš praktikos.','Ilgi tekstai ir trumpos pastabos. Pasirink temą arba ieškok to, kas įdomu.','Ieškoti užrašuose…','Originalo kalba','Visos kalbos','Visi','Apie','Mokytis. Patirti. Užrašyti.','Viešas mokymosi sąsiuvinis apie sportą, kalbas, sprendimus ir santykius. Palieku vietos persigalvoti. Mintys keičiasi. Užrašai lieka.','Kūnas ir praktika','Mokytis mokytis','Mintys ir santykiai','Originalūs tekstai palikti tokie, kokie parašyti: lietuviškai, angliškai arba abiem kalbomis.','Vertimas, parengtas pasitelkus DI. Originalus tekstas išsaugotas atskirai.','Skaityti originalą','Originalus tekstas · Raw','Atsisiųsti originalą (.md)','Visi užrašai','Nieko nerasta.','Išvalyti filtrus','užrašai','Vertimas','Originalas','Pereiti prie turinio','min.','Kodėl rašau','Abstraktus Alpių peizažas','Mintys keičiasi. Užrašai lieka.'
],
en:[
'A PERSONAL LEARNING NOTEBOOK','I write to understand.','Sport, languages and reflections. Experiences I return to, questions I’m still exploring.','Explore the notebook','Notes from practice.','Long essays and short observations. Choose a topic or follow your curiosity.','Search the notebook…','Original language','All languages','All','About','Learn. Experience. Write.','A public learning notebook about sport, languages, decisions and relationships. There is room to change my mind. Thoughts evolve. Notes remain.','Body and practice','Learning to learn','Thoughts and relationships','Original texts remain exactly as written: Lithuanian, English, or a mixture of both.','AI-assisted translation. The original text is preserved separately.','Read the original','Original text · Raw','Download original (.md)','All notes','No notes found.','Clear filters','notes','Translation','Original','Skip to content','min','Why I write','Abstract Alpine landscape','Thoughts evolve. Notes remain.'
],
es:[
'UN CUADERNO PERSONAL DE APRENDIZAJE','Escribo para entender.','Deporte, idiomas y reflexiones. Experiencias a las que vuelvo, preguntas que sigo explorando.','Explorar el cuaderno','Notas de la práctica.','Ensayos largos y observaciones breves. Elige un tema o sigue tu curiosidad.','Buscar en el cuaderno…','Idioma original','Todos los idiomas','Todo','Acerca de','Aprender. Vivir. Escribir.','Un cuaderno público sobre deporte, idiomas, decisiones y relaciones. Hay espacio para cambiar de opinión. Las ideas evolucionan. Las notas permanecen.','Cuerpo y práctica','Aprender a aprender','Pensamientos y relaciones','Los textos originales se conservan tal como fueron escritos: en lituano, inglés o una mezcla de ambos.','Traducción asistida por IA. El texto original se conserva por separado.','Leer el original','Texto original · Raw','Descargar original (.md)','Todas las notas','No se encontraron notas.','Borrar filtros','notas','Traducción','Original','Ir al contenido','min','Por qué escribo','Paisaje alpino abstracto','Las ideas evolucionan. Las notas permanecen.'
],
pt:[
'UM CADERNO PESSOAL DE APRENDIZAGEM','Escrevo para compreender.','Desporto, línguas e reflexões. Experiências a que regresso, perguntas que continuo a explorar.','Explorar o caderno','Notas da prática.','Ensaios longos e observações breves. Escolhe um tema ou segue a tua curiosidade.','Pesquisar no caderno…','Língua original','Todas as línguas','Tudo','Sobre','Aprender. Viver. Escrever.','Um caderno público sobre desporto, línguas, decisões e relações. Há espaço para mudar de ideias. Os pensamentos mudam. As notas ficam.','Corpo e prática','Aprender a aprender','Pensamentos e relações','Os textos originais mantêm-se tal como foram escritos: em lituano, inglês ou numa mistura dos dois.','Tradução assistida por IA. O texto original é preservado separadamente.','Ler o original','Texto original · Raw','Descarregar original (.md)','Todas as notas','Nenhuma nota encontrada.','Limpar filtros','notas','Tradução','Original','Ir para o conteúdo','min','Porque escrevo','Paisagem alpina abstrata','Os pensamentos mudam. As notas ficam.'
],
de:[
'EIN PERSÖNLICHES LERNNOTIZBUCH','Ich schreibe, um zu verstehen.','Sport, Sprachen und Gedanken. Erfahrungen, zu denen ich zurückkehre. Fragen, denen ich weiter nachgehe.','Notizbuch erkunden','Notizen aus der Praxis.','Lange Essays und kurze Beobachtungen. Wähle ein Thema oder folge deiner Neugier.','Notizbuch durchsuchen…','Originalsprache','Alle Sprachen','Alle','Über','Lernen. Erleben. Schreiben.','Ein öffentliches Lernnotizbuch über Sport, Sprachen, Entscheidungen und Beziehungen. Es bleibt Raum, meine Meinung zu ändern. Gedanken verändern sich. Notizen bleiben.','Körper und Praxis','Lernen lernen','Gedanken und Beziehungen','Originaltexte bleiben genau wie geschrieben: auf Litauisch, Englisch oder in beiden Sprachen.','KI-gestützte Übersetzung. Der Originaltext bleibt separat erhalten.','Original lesen','Originaltext · Raw','Original herunterladen (.md)','Alle Notizen','Keine Notizen gefunden.','Filter zurücksetzen','Notizen','Übersetzung','Original','Zum Inhalt springen','Min.','Warum ich schreibe','Abstrakte Alpenlandschaft','Gedanken verändern sich. Notizen bleiben.'
],
fr:[
'UN CARNET PERSONNEL D’APPRENTISSAGE','J’écris pour comprendre.','Sport, langues et réflexions. Des expériences auxquelles je reviens, des questions que j’explore encore.','Explorer le carnet','Notes de la pratique.','Longs essais et brèves observations. Choisissez un sujet ou suivez votre curiosité.','Rechercher dans le carnet…','Langue originale','Toutes les langues','Tout','À propos','Apprendre. Vivre. Écrire.','Un carnet public sur le sport, les langues, les décisions et les relations. Il reste de la place pour changer d’avis. Les pensées évoluent. Les notes restent.','Corps et pratique','Apprendre à apprendre','Pensées et relations','Les textes originaux restent tels qu’ils ont été écrits : en lituanien, en anglais ou dans les deux langues.','Traduction assistée par IA. Le texte original est conservé séparément.','Lire l’original','Texte original · Raw','Télécharger l’original (.md)','Toutes les notes','Aucune note trouvée.','Effacer les filtres','notes','Traduction','Original','Aller au contenu','min','Pourquoi j’écris','Paysage alpin abstrait','Les pensées évoluent. Les notes restent.'
],
it:[
'UN QUADERNO PERSONALE DI APPRENDIMENTO','Scrivo per capire.','Sport, lingue e riflessioni. Esperienze a cui torno, domande che continuo a esplorare.','Esplora il quaderno','Appunti dalla pratica.','Saggi lunghi e brevi osservazioni. Scegli un tema o segui la curiosità.','Cerca nel quaderno…','Lingua originale','Tutte le lingue','Tutto','Informazioni','Imparare. Vivere. Scrivere.','Un quaderno pubblico su sport, lingue, decisioni e relazioni. C’è spazio per cambiare idea. I pensieri cambiano. Gli appunti restano.','Corpo e pratica','Imparare a imparare','Pensieri e relazioni','I testi originali restano esattamente come sono stati scritti: in lituano, inglese o in entrambe le lingue.','Traduzione assistita dall’IA. Il testo originale è conservato separatamente.','Leggi l’originale','Testo originale · Raw','Scarica l’originale (.md)','Tutti gli appunti','Nessun appunto trovato.','Cancella filtri','appunti','Traduzione','Originale','Vai al contenuto','min','Perché scrivo','Paesaggio alpino astratto','I pensieri cambiano. Gli appunti restano.'
],
ru:[
'ЛИЧНАЯ ТЕТРАДЬ ОБУЧЕНИЯ','Пишу, чтобы понять.','Спорт, языки и размышления. Опыт, к которому я возвращаюсь. Вопросы, которые ещё исследую.','Открыть тетрадь','Заметки из практики.','Длинные эссе и короткие наблюдения. Выберите тему или следуйте любопытству.','Поиск по тетради…','Язык оригинала','Все языки','Все','О проекте','Учиться. Пробовать. Писать.','Открытая тетрадь о спорте, языках, решениях и отношениях. Здесь есть место, чтобы передумать. Мысли меняются. Заметки остаются.','Тело и практика','Учиться учиться','Мысли и отношения','Оригинальные тексты сохранены точно как написаны: на литовском, английском или обоих языках.','Перевод с помощью ИИ. Оригинальный текст сохранён отдельно.','Читать оригинал','Оригинальный текст · Raw','Скачать оригинал (.md)','Все заметки','Заметки не найдены.','Сбросить фильтры','заметок','Перевод','Оригинал','К содержимому','мин','Почему я пишу','Абстрактный альпийский пейзаж','Мысли меняются. Заметки остаются.'
],
da:[
'EN PERSONLIG LÆRINGSNOTESBOG','Jeg skriver for at forstå.','Sport, sprog og refleksioner. Erfaringer, jeg vender tilbage til. Spørgsmål, jeg stadig undersøger.','Udforsk notesbogen','Noter fra praksis.','Lange essays og korte observationer. Vælg et emne, eller følg din nysgerrighed.','Søg i notesbogen…','Originalsprog','Alle sprog','Alle','Om','Lære. Opleve. Skrive.','En offentlig notesbog om sport, sprog, beslutninger og relationer. Der er plads til at skifte mening. Tanker ændrer sig. Noter bliver.','Krop og praksis','At lære at lære','Tanker og relationer','Originalteksterne bevares præcis som skrevet: på litauisk, engelsk eller begge sprog.','AI-assisteret oversættelse. Originalteksten bevares separat.','Læs originalen','Originaltekst · Raw','Download original (.md)','Alle noter','Ingen noter fundet.','Nulstil filtre','noter','Oversættelse','Original','Gå til indhold','min','Hvorfor jeg skriver','Abstrakt alpelandskab','Tanker ændrer sig. Noter bliver.'
]};
export const copy = Object.fromEntries(Object.entries(data).map(([lang,values])=>{
 if(values.length!==keys.length) throw Error(`UI translation mismatch: ${lang}`);
 return [lang,Object.fromEntries(keys.map((key,i)=>[key,values[i]]))];
}));
