import type {Edition,Category} from './posts';
export const labels:Record<Edition,{recent:string;previous:string;next:string;updated:string;aboutLink:string;original:string;translation:string;older:string;intro:Record<Category,string>}>={
 original:{recent:'Naujausi puslapiai',previous:'Ankstesnis užrašas',next:'Kitas užrašas',updated:'Atnaujinta',aboutLink:'Apie sąsiuvinį',original:'ORIGINALAS',translation:'Vertimas',older:'Originalas atnaujintas po šio vertimo.',intro:{Sportas:'Kūnas, rizika ir praktika. Ką išmokstu nardydamas, skrisdamas ir treniruodamasis.',Kalbos:'Kalbų mokymasis, metodai ir kasdienė praktika. Mokytis mokytis.',Protas:'Mintys, sprendimai ir santykiai. Bandymas aiškiau matyti tai, kas vyksta.',Blog:'Pastabos apie patį sąsiuvinį ir visa, kas dar nerado savo vietos.'}},
 en:{recent:'Recent pages',previous:'Previous note',next:'Next note',updated:'Updated',aboutLink:'About this notebook',original:'ORIGINAL',translation:'Translation',older:'The original has been updated since this translation.',intro:{Sportas:'Body, risk and practice. Lessons from diving, flying and training.',Kalbos:'Languages, methods and daily practice. Learning how to learn.',Protas:'Thoughts, decisions and relationships. Trying to see more clearly.',Blog:'Notes about the notebook, and things that have yet to find their place.'}},
 es:{recent:'Páginas recientes',previous:'Nota anterior',next:'Nota siguiente',updated:'Actualizado',aboutLink:'Sobre el cuaderno',original:'ORIGINAL',translation:'Traducción',older:'El original se ha actualizado después de esta traducción.',intro:{Sportas:'Cuerpo, riesgo y práctica. Lecciones del buceo, el vuelo y el entrenamiento.',Kalbos:'Idiomas, métodos y práctica diaria. Aprender a aprender.',Protas:'Pensamientos, decisiones y relaciones. Intentar ver con más claridad.',Blog:'Notas sobre el cuaderno y lo que aún no tiene su lugar.'}},
 pt:{recent:'Páginas recentes',previous:'Nota anterior',next:'Nota seguinte',updated:'Atualizado',aboutLink:'Sobre o caderno',original:'ORIGINAL',translation:'Tradução',older:'O original foi atualizado depois desta tradução.',intro:{Sportas:'Corpo, risco e prática. Lições do mergulho, do voo e do treino.',Kalbos:'Línguas, métodos e prática diária. Aprender a aprender.',Protas:'Pensamentos, decisões e relações. Tentar ver com mais clareza.',Blog:'Notas sobre o caderno e o que ainda não encontrou o seu lugar.'}},
 de:{recent:'Neue Seiten',previous:'Vorherige Notiz',next:'Nächste Notiz',updated:'Aktualisiert',aboutLink:'Über das Notizbuch',original:'ORIGINAL',translation:'Übersetzung',older:'Das Original wurde nach dieser Übersetzung aktualisiert.',intro:{Sportas:'Körper, Risiko und Praxis. Erfahrungen beim Tauchen, Fliegen und Trainieren.',Kalbos:'Sprachen, Methoden und tägliche Praxis. Lernen lernen.',Protas:'Gedanken, Entscheidungen und Beziehungen. Der Versuch, klarer zu sehen.',Blog:'Notizen über das Notizbuch und Dinge, die noch ihren Platz suchen.'}},
 fr:{recent:'Pages récentes',previous:'Note précédente',next:'Note suivante',updated:'Mis à jour',aboutLink:'À propos du carnet',original:'ORIGINAL',translation:'Traduction',older:'L’original a été mis à jour après cette traduction.',intro:{Sportas:'Corps, risque et pratique. Leçons de plongée, de vol et d’entraînement.',Kalbos:'Langues, méthodes et pratique quotidienne. Apprendre à apprendre.',Protas:'Pensées, décisions et relations. Essayer de voir plus clair.',Blog:'Notes sur le carnet et ce qui cherche encore sa place.'}},
 it:{recent:'Pagine recenti',previous:'Appunto precedente',next:'Appunto successivo',updated:'Aggiornato',aboutLink:'Informazioni sul quaderno',original:'ORIGINALE',translation:'Traduzione',older:'L’originale è stato aggiornato dopo questa traduzione.',intro:{Sportas:'Corpo, rischio e pratica. Lezioni dalle immersioni, dal volo e dall’allenamento.',Kalbos:'Lingue, metodi e pratica quotidiana. Imparare a imparare.',Protas:'Pensieri, decisioni e relazioni. Cercare di vedere più chiaramente.',Blog:'Appunti sul quaderno e ciò che cerca ancora il proprio posto.'}},
 ru:{recent:'Новые страницы',previous:'Предыдущая заметка',next:'Следующая заметка',updated:'Обновлено',aboutLink:'Об этой тетради',original:'ОРИГИНАЛ',translation:'Перевод',older:'Оригинал обновлён после этого перевода.',intro:{Sportas:'Тело, риск и практика. Уроки погружений, полётов и тренировок.',Kalbos:'Языки, методы и ежедневная практика. Учиться учиться.',Protas:'Мысли, решения и отношения. Попытка видеть яснее.',Blog:'Заметки о тетради и о том, что ещё ищет своё место.'}},
 da:{recent:'Nye sider',previous:'Forrige note',next:'Næste note',updated:'Opdateret',aboutLink:'Om notesbogen',original:'ORIGINAL',translation:'Oversættelse',older:'Originalen er opdateret efter denne oversættelse.',intro:{Sportas:'Krop, risiko og praksis. Erfaringer fra dykning, flyvning og træning.',Kalbos:'Sprog, metoder og daglig praksis. At lære at lære.',Protas:'Tanker, beslutninger og relationer. Et forsøg på at se klarere.',Blog:'Noter om notesbogen og det, der stadig søger sin plads.'}},
};
